import { defineConfig } from 'vite'
import { fileURLToPath, URL } from 'node:url'
import { resolve } from 'path'
import vue from '@vitejs/plugin-vue2'
import replace from '@rollup/plugin-replace'

export default defineConfig(({ command, mode, ssrBuild }) => {
    return {
        plugins: [
            vue(),
            replace({
                values: {
                    '__WORLD__': JSON.stringify(require('./src/data/world.topo.json')),
                    '__ABW__': JSON.stringify(require('./src/data/abw.topo.json')),
                    '__AFG__': JSON.stringify(require('./src/data/afg.topo.json')),
                    '__AGO__': JSON.stringify(require('./src/data/ago.topo.json')),
                    '__AIA__': JSON.stringify(require('./src/data/aia.topo.json')),
                    '__ALB__': JSON.stringify(require('./src/data/alb.topo.json')),
                    '__ALD__': JSON.stringify(require('./src/data/ald.topo.json')),
                    '__AND__': JSON.stringify(require('./src/data/and.topo.json')),
                    '__ARE__': JSON.stringify(require('./src/data/are.topo.json')),
                    '__ARG__': JSON.stringify(require('./src/data/arg.topo.json')),
                    '__ARM__': JSON.stringify(require('./src/data/arm.topo.json')),
                    // '__ASM__': JSON.stringify(require('./src/data/asm.topo.json')),
                    '__ATA__': JSON.stringify(require('./src/data/ata.topo.json')),
                    '__ATC__': JSON.stringify(require('./src/data/atc.topo.json')),
                    // '__ATF__': JSON.stringify(require('./src/data/atf.topo.json')),
                    '__ATG__': JSON.stringify(require('./src/data/atg.topo.json')),
                    '__AUS__': JSON.stringify(require('./src/data/aus.topo.json')),
                    '__AUT__': JSON.stringify(require('./src/data/aut.topo.json')),
                    '__AZE__': JSON.stringify(require('./src/data/aze.topo.json')),
                    '__BDI__': JSON.stringify(require('./src/data/bdi.topo.json')),
                    '__BEL__': JSON.stringify(require('./src/data/bel.topo.json')),
                    '__BEN__': JSON.stringify(require('./src/data/ben.topo.json')),
                    '__BFA__': JSON.stringify(require('./src/data/bfa.topo.json')),
                    '__BGD__': JSON.stringify(require('./src/data/bgd.topo.json')),
                    '__BGR__': JSON.stringify(require('./src/data/bgr.topo.json')),
                    '__BHR__': JSON.stringify(require('./src/data/bhr.topo.json')),
                    // '__BHS__': JSON.stringify(require('./src/data/bhs.topo.json')),
                    '__BIH__': JSON.stringify(require('./src/data/bih.topo.json')),
                    '__BJN__': JSON.stringify(require('./src/data/bjn.topo.json')),
                    '__BLM__': JSON.stringify(require('./src/data/blm.topo.json')),
                    '__BLR__': JSON.stringify(require('./src/data/blr.topo.json')),
                    '__BLZ__': JSON.stringify(require('./src/data/blz.topo.json')),
                    // '__BMU__': JSON.stringify(require('./src/data/bmu.topo.json')),
                    '__BOL__': JSON.stringify(require('./src/data/bol.topo.json')),
                    '__BRA__': JSON.stringify(require('./src/data/bra.topo.json')),
                    '__BRB__': JSON.stringify(require('./src/data/brb.topo.json')),
                    '__BRN__': JSON.stringify(require('./src/data/brn.topo.json')),
                    '__BTN__': JSON.stringify(require('./src/data/btn.topo.json')),
                    '__NOR__': JSON.stringify(require('./src/data/nor.topo.json')),
                    '__BWA__': JSON.stringify(require('./src/data/bwa.topo.json')),
                    // '__CAF__': JSON.stringify(require('./src/data/caf.topo.json')),
                    '__CAN__': JSON.stringify(require('./src/data/can.topo.json')),
                    '__CHE__': JSON.stringify(require('./src/data/che.topo.json')),
                    // '__CHL__': JSON.stringify(require('./src/data/chl.topo.json')),
                    '__CHN__': JSON.stringify(require('./src/data/chn.topo.json')),
                    // '__CIV__': JSON.stringify(require('./src/data/civ.topo.json')),
                    '__CLP__': JSON.stringify(require('./src/data/clp.topo.json')),
                    '__CMR__': JSON.stringify(require('./src/data/cmr.topo.json')),
                    '__COD__': JSON.stringify(require('./src/data/cod.topo.json')),
                    '__COG__': JSON.stringify(require('./src/data/cog.topo.json')),
                    '__COK__': JSON.stringify(require('./src/data/cok.topo.json')),
                    '__COL__': JSON.stringify(require('./src/data/col.topo.json')),
                    '__COM__': JSON.stringify(require('./src/data/com.topo.json')),
                    '__CPV__': JSON.stringify(require('./src/data/cpv.topo.json')),
                    '__CRI__': JSON.stringify(require('./src/data/cri.topo.json')),
                    '__CSI__': JSON.stringify(require('./src/data/csi.topo.json')),
                    '__CUB__': JSON.stringify(require('./src/data/cub.topo.json')),
                    '__CUW__': JSON.stringify(require('./src/data/cuw.topo.json')),
                    '__CYM__': JSON.stringify(require('./src/data/cym.topo.json')),
                    '__CYN__': JSON.stringify(require('./src/data/cyn.topo.json')),
                    '__CYP__': JSON.stringify(require('./src/data/cyp.topo.json')),
                    '__CZE__': JSON.stringify(require('./src/data/cze.topo.json')),
                    '__DEU__': JSON.stringify(require('./src/data/deu.topo.json')),
                    '__DJI__': JSON.stringify(require('./src/data/dji.topo.json')),
                    '__DMA__': JSON.stringify(require('./src/data/dma.topo.json')),
                    '__DNK__': JSON.stringify(require('./src/data/dnk.topo.json')),
                    '__DOM__': JSON.stringify(require('./src/data/dom.topo.json')),
                    // '__DZA__': JSON.stringify(require('./src/data/dza.topo.json')),
                    '__ECU__': JSON.stringify(require('./src/data/ecu.topo.json')),
                    // '__EGY__': JSON.stringify(require('./src/data/egy.topo.json')),
                    '__ERI__': JSON.stringify(require('./src/data/eri.topo.json')),
                    '__ESB__': JSON.stringify(require('./src/data/esb.topo.json')),
                    '__ESP__': JSON.stringify(require('./src/data/esp.topo.json')),
                    '__EST__': JSON.stringify(require('./src/data/est.topo.json')),
                    '__ETH__': JSON.stringify(require('./src/data/eth.topo.json')),
                    '__FIN__': JSON.stringify(require('./src/data/fin.topo.json')),
                    '__FJI__': JSON.stringify(require('./src/data/fji.topo.json')),
                    '__FLK__': JSON.stringify(require('./src/data/flk.topo.json')),
                    // '__FRA__': JSON.stringify(require('./src/data/fra.topo.json')),
                    '__FRO__': JSON.stringify(require('./src/data/fro.topo.json')),
                    '__FSM__': JSON.stringify(require('./src/data/fsm.topo.json')),
                    '__GAB__': JSON.stringify(require('./src/data/gab.topo.json')),
                    '__PSX__': JSON.stringify(require('./src/data/psx.topo.json')),
                    '__GBR__': JSON.stringify(require('./src/data/gbr.topo.json')),
                    '__GEO__': JSON.stringify(require('./src/data/geo.topo.json')),
                    '__GGY__': JSON.stringify(require('./src/data/ggy.topo.json')),
                    '__GHA__': JSON.stringify(require('./src/data/gha.topo.json')),
                    '__GIB__': JSON.stringify(require('./src/data/gib.topo.json')),
                    '__GIN__': JSON.stringify(require('./src/data/gin.topo.json')),
                    '__GMB__': JSON.stringify(require('./src/data/gmb.topo.json')),
                    '__GNB__': JSON.stringify(require('./src/data/gnb.topo.json')),
                    '__GNQ__': JSON.stringify(require('./src/data/gnq.topo.json')),
                    '__GRC__': JSON.stringify(require('./src/data/grc.topo.json')),
                    '__GRD__': JSON.stringify(require('./src/data/grd.topo.json')),
                    '__GRL__': JSON.stringify(require('./src/data/grl.topo.json')),
                    '__GTM__': JSON.stringify(require('./src/data/gtm.topo.json')),
                    '__GUM__': JSON.stringify(require('./src/data/gum.topo.json')),
                    '__GUY__': JSON.stringify(require('./src/data/guy.topo.json')),
                    '__HKG__': JSON.stringify(require('./src/data/hkg.topo.json')),
                    '__HMD__': JSON.stringify(require('./src/data/hmd.topo.json')),
                    '__HND__': JSON.stringify(require('./src/data/hnd.topo.json')),
                    '__HRV__': JSON.stringify(require('./src/data/hrv.topo.json')),
                    // '__HTI__': JSON.stringify(require('./src/data/hti.topo.json')),
                    '__HUN__': JSON.stringify(require('./src/data/hun.topo.json')),
                    '__IDN__': JSON.stringify(require('./src/data/idn.topo.json')),
                    '__IMN__': JSON.stringify(require('./src/data/imn.topo.json')),
                    '__IND__': JSON.stringify(require('./src/data/ind.topo.json')),
                    '__IOA__': JSON.stringify(require('./src/data/ioa.topo.json')),
                    '__IOT__': JSON.stringify(require('./src/data/iot.topo.json')),
                    '__IRL__': JSON.stringify(require('./src/data/irl.topo.json')),
                    '__IRN__': JSON.stringify(require('./src/data/irn.topo.json')),
                    // '__IRQ__': JSON.stringify(require('./src/data/irq.topo.json')),
                    '__ISL__': JSON.stringify(require('./src/data/isl.topo.json')),
                    '__ISR__': JSON.stringify(require('./src/data/isr.topo.json')),
                    // '__ITA__': JSON.stringify(require('./src/data/ita.topo.json')),
                    '__JAM__': JSON.stringify(require('./src/data/jam.topo.json')),
                    '__JEY__': JSON.stringify(require('./src/data/jey.topo.json')),
                    '__JOR__': JSON.stringify(require('./src/data/jor.topo.json')),
                    '__JPN__': JSON.stringify(require('./src/data/jpn.topo.json')),
                    '__KAB__': JSON.stringify(require('./src/data/kab.topo.json')),
                    '__KAS__': JSON.stringify(require('./src/data/kas.topo.json')),
                    '__KAZ__': JSON.stringify(require('./src/data/kaz.topo.json')),
                    '__KEN__': JSON.stringify(require('./src/data/ken.topo.json')),
                    '__KGZ__': JSON.stringify(require('./src/data/kgz.topo.json')),
                    '__KHM__': JSON.stringify(require('./src/data/khm.topo.json')),
                    '__KIR__': JSON.stringify(require('./src/data/kir.topo.json')),
                    '__KNA__': JSON.stringify(require('./src/data/kna.topo.json')),
                    '__KOR__': JSON.stringify(require('./src/data/kor.topo.json')),
                    '__KOS__': JSON.stringify(require('./src/data/kos.topo.json')),
                    '__KWT__': JSON.stringify(require('./src/data/kwt.topo.json')),
                    '__LAO__': JSON.stringify(require('./src/data/lao.topo.json')),
                    '__LBN__': JSON.stringify(require('./src/data/lbn.topo.json')),
                    '__LBR__': JSON.stringify(require('./src/data/lbr.topo.json')),
                    // '__LBY__': JSON.stringify(require('./src/data/lby.topo.json')),
                    '__LCA__': JSON.stringify(require('./src/data/lca.topo.json')),
                    '__LIE__': JSON.stringify(require('./src/data/lie.topo.json')),
                    '__LKA__': JSON.stringify(require('./src/data/lka.topo.json')),
                    // '__LSO__': JSON.stringify(require('./src/data/lso.topo.json')),
                    '__LTU__': JSON.stringify(require('./src/data/ltu.topo.json')),
                    '__LUX__': JSON.stringify(require('./src/data/lux.topo.json')),
                    '__LVA__': JSON.stringify(require('./src/data/lva.topo.json')),
                    '__MAC__': JSON.stringify(require('./src/data/mac.topo.json')),
                    '__MAF__': JSON.stringify(require('./src/data/maf.topo.json')),
                    '__MAR__': JSON.stringify(require('./src/data/mar.topo.json')),
                    '__MCO__': JSON.stringify(require('./src/data/mco.topo.json')),
                    '__MDA__': JSON.stringify(require('./src/data/mda.topo.json')),
                    // '__MDG__': JSON.stringify(require('./src/data/mdg.topo.json')),
                    '__MDV__': JSON.stringify(require('./src/data/mdv.topo.json')),
                    // '__MEX__': JSON.stringify(require('./src/data/mex.topo.json')),
                    '__MHL__': JSON.stringify(require('./src/data/mhl.topo.json')),
                    '__MKD__': JSON.stringify(require('./src/data/mkd.topo.json')),
                    '__MLI__': JSON.stringify(require('./src/data/mli.topo.json')),
                    // '__MLT__': JSON.stringify(require('./src/data/mlt.topo.json')),
                    '__MMR__': JSON.stringify(require('./src/data/mmr.topo.json')),
                    '__MNE__': JSON.stringify(require('./src/data/mne.topo.json')),
                    '__MNG__': JSON.stringify(require('./src/data/mng.topo.json')),
                    '__MNP__': JSON.stringify(require('./src/data/mnp.topo.json')),
                    '__MOZ__': JSON.stringify(require('./src/data/moz.topo.json')),
                    '__MRT__': JSON.stringify(require('./src/data/mrt.topo.json')),
                    '__MSR__': JSON.stringify(require('./src/data/msr.topo.json')),
                    '__MUS__': JSON.stringify(require('./src/data/mus.topo.json')),
                    '__MWI__': JSON.stringify(require('./src/data/mwi.topo.json')),
                    '__MYS__': JSON.stringify(require('./src/data/mys.topo.json')),
                    '__NAM__': JSON.stringify(require('./src/data/nam.topo.json')),
                    '__NCL__': JSON.stringify(require('./src/data/ncl.topo.json')),
                    '__NER__': JSON.stringify(require('./src/data/ner.topo.json')),
                    '__NFK__': JSON.stringify(require('./src/data/nfk.topo.json')),
                    '__NGA__': JSON.stringify(require('./src/data/nga.topo.json')),
                    '__NIC__': JSON.stringify(require('./src/data/nic.topo.json')),
                    '__NIU__': JSON.stringify(require('./src/data/niu.topo.json')),
                    '__NLD__': JSON.stringify(require('./src/data/nld.topo.json')),
                    '__NPL__': JSON.stringify(require('./src/data/npl.topo.json')),
                    '__NRU__': JSON.stringify(require('./src/data/nru.topo.json')),
                    '__NUL__': JSON.stringify(require('./src/data/_nul.topo.json')),
                    // '__NZL__': JSON.stringify(require('./src/data/nzl.topo.json')),
                    '__OMN__': JSON.stringify(require('./src/data/omn.topo.json')),
                    '__PAK__': JSON.stringify(require('./src/data/pak.topo.json')),
                    '__PAN__': JSON.stringify(require('./src/data/pan.topo.json')),
                    '__PCN__': JSON.stringify(require('./src/data/pcn.topo.json')),
                    '__PER__': JSON.stringify(require('./src/data/per.topo.json')),
                    '__PGA__': JSON.stringify(require('./src/data/pga.topo.json')),
                    '__PHL__': JSON.stringify(require('./src/data/phl.topo.json')),
                    '__PLW__': JSON.stringify(require('./src/data/plw.topo.json')),
                    '__PNG__': JSON.stringify(require('./src/data/png.topo.json')),
                    '__POL__': JSON.stringify(require('./src/data/pol.topo.json')),
                    '__PRI__': JSON.stringify(require('./src/data/pri.topo.json')),
                    // '__PRK__': JSON.stringify(require('./src/data/prk.topo.json')),
                    '__PRT__': JSON.stringify(require('./src/data/prt.topo.json')),
                    '__PRY__': JSON.stringify(require('./src/data/pry.topo.json')),
                    '__PYF__': JSON.stringify(require('./src/data/pyf.topo.json')),
                    '__QAT__': JSON.stringify(require('./src/data/qat.topo.json')),
                    '__ROU__': JSON.stringify(require('./src/data/rou.topo.json')),
                    // '__RUS__': JSON.stringify(require('./src/data/rus.topo.json')),
                    '__RWA__': JSON.stringify(require('./src/data/rwa.topo.json')),
                    '__SAH__': JSON.stringify(require('./src/data/sah.topo.json')),
                    // '__SAU__': JSON.stringify(require('./src/data/sau.topo.json')),
                    '__SCR__': JSON.stringify(require('./src/data/scr.topo.json')),
                    '__SDN__': JSON.stringify(require('./src/data/sdn.topo.json')),
                    '__SDS__': JSON.stringify(require('./src/data/sds.topo.json')),
                    '__SEN__': JSON.stringify(require('./src/data/sen.topo.json')),
                    '__SER__': JSON.stringify(require('./src/data/ser.topo.json')),
                    '__SGP__': JSON.stringify(require('./src/data/sgp.topo.json')),
                    '__SGS__': JSON.stringify(require('./src/data/sgs.topo.json')),
                    '__SHN__': JSON.stringify(require('./src/data/shn.topo.json')),
                    '__SLB__': JSON.stringify(require('./src/data/slb.topo.json')),
                    '__SLE__': JSON.stringify(require('./src/data/sle.topo.json')),
                    '__SLV__': JSON.stringify(require('./src/data/slv.topo.json')),
                    '__SMR__': JSON.stringify(require('./src/data/smr.topo.json')),
                    '__SOL__': JSON.stringify(require('./src/data/sol.topo.json')),
                    '__SOM__': JSON.stringify(require('./src/data/som.topo.json')),
                    '__SPM__': JSON.stringify(require('./src/data/spm.topo.json')),
                    '__SRB__': JSON.stringify(require('./src/data/srb.topo.json')),
                    '__STP__': JSON.stringify(require('./src/data/stp.topo.json')),
                    '__SUR__': JSON.stringify(require('./src/data/sur.topo.json')),
                    '__SVK__': JSON.stringify(require('./src/data/svk.topo.json')),
                    '__SVN__': JSON.stringify(require('./src/data/svn.topo.json')),
                    '__SWE__': JSON.stringify(require('./src/data/swe.topo.json')),
                    '__SWZ__': JSON.stringify(require('./src/data/swz.topo.json')),
                    '__SXM__': JSON.stringify(require('./src/data/sxm.topo.json')),
                    // '__SYC__': JSON.stringify(require('./src/data/syc.topo.json')),
                    // '__SYR__': JSON.stringify(require('./src/data/syr.topo.json')),
                    '__TCA__': JSON.stringify(require('./src/data/tca.topo.json')),
                    // '__TCD__': JSON.stringify(require('./src/data/tcd.topo.json')),
                    '__TGO__': JSON.stringify(require('./src/data/tgo.topo.json')),
                    '__THA__': JSON.stringify(require('./src/data/tha.topo.json')),
                    '__TJK__': JSON.stringify(require('./src/data/tjk.topo.json')),
                    '__TKM__': JSON.stringify(require('./src/data/tkm.topo.json')),
                    '__TLS__': JSON.stringify(require('./src/data/tls.topo.json')),
                    // '__TON__': JSON.stringify(require('./src/data/ton.topo.json')),
                    '__TTO__': JSON.stringify(require('./src/data/tto.topo.json')),
                    '__TUN__': JSON.stringify(require('./src/data/tun.topo.json')),
                    '__TUR__': JSON.stringify(require('./src/data/tur.topo.json')),
                    '__TUV__': JSON.stringify(require('./src/data/tuv.topo.json')),
                    '__TWN__': JSON.stringify(require('./src/data/twn.topo.json')),
                    '__TZA__': JSON.stringify(require('./src/data/tza.topo.json')),
                    '__UGA__': JSON.stringify(require('./src/data/uga.topo.json')),
                    // '__UKR__': JSON.stringify(require('./src/data/ukr.topo.json')),
                    '__UMI__': JSON.stringify(require('./src/data/umi.topo.json')),
                    '__URY__': JSON.stringify(require('./src/data/ury.topo.json')),
                    '__USA__': JSON.stringify(require('./src/data/usa.topo.json')),
                    '__USG__': JSON.stringify(require('./src/data/usg.topo.json')),
                    '__UZB__': JSON.stringify(require('./src/data/uzb.topo.json')),
                    '__VAT__': JSON.stringify(require('./src/data/vat.topo.json')),
                    '__VCT__': JSON.stringify(require('./src/data/vct.topo.json')),
                    '__VEN__': JSON.stringify(require('./src/data/ven.topo.json')),
                    '__VGB__': JSON.stringify(require('./src/data/vgb.topo.json')),
                    '__VIR__': JSON.stringify(require('./src/data/vir.topo.json')),
                    '__VNM__': JSON.stringify(require('./src/data/vnm.topo.json')),
                    '__VUT__': JSON.stringify(require('./src/data/vut.topo.json')),
                    '__WLF__': JSON.stringify(require('./src/data/wlf.topo.json')),
                    '__WSB__': JSON.stringify(require('./src/data/wsb.topo.json')),
                    // '__WSM__': JSON.stringify(require('./src/data/wsm.topo.json')),
                    // '__YEM__': JSON.stringify(require('./src/data/yem.topo.json')),
                    '__ZAF__': JSON.stringify(require('./src/data/zaf.topo.json')),
                    '__ZMB__': JSON.stringify(require('./src/data/zmb.topo.json')),
                    '__ZWE__': JSON.stringify(require('./src/data/zwe.topo.json'))
                },
                include: './src/utils/topology.js',
                preventAssignment: true
            })
        ],
        server: {
            port: 8080
        },
        resolve: {
            alias: {
                '@': fileURLToPath(new URL('./src', import.meta.url))
            },
            extensions: ['.mjs', '.js', '.ts', '.jsx', '.tsx', '.json', '.vue']
        }
    }
})
