const topology = {
    worldTopo: '__WORLD__',
    abwTopo: '__ABW__',
    afgTopo: '__AFG__',
    agoTopo: '__AGO__',
    aiaTopo: '__AIA__',
    albTopo: '__ALB__',
    aldTopo: '__ALD__',
    andTopo: '__AND__',
    areTopo: '__ARE__',
    argTopo: '__ARG__',
    armTopo: '__ARM__',
    // asmTopo: '__ASM__',
    ataTopo: '__ATA__',
    atcTopo: '__ATC__',
    // atfTopo: '__ATF__',
    atgTopo: '__ATG__',
    ausTopo: '__AUS__',
    autTopo: '__AUT__',
    azeTopo: '__AZE__',
    bdiTopo: '__BDI__',
    belTopo: '__BEL__',
    benTopo: '__BEN__',
    bfaTopo: '__BFA__',
    bgdTopo: '__BGD__',
    bgrTopo: '__BGR__',
    bhrTopo: '__BHR__',
    // bhsTopo: '__BHS__',
    bihTopo: '__BIH__',
    bjnTopo: '__BJN__',
    blmTopo: '__BLM__',
    blrTopo: '__BLR__',
    blzTopo: '__BLZ__',
    // bmuTopo: '__BMU__',
    bolTopo: '__BOL__',
    braTopo: '__BRA__',
    brbTopo: '__BRB__',
    brnTopo: '__BRN__',
    btnTopo: '__BTN__',
    norTopo: '__NOR__',
    bwaTopo: '__BWA__',
    // cafTopo: '__CAF__',
    canTopo: '__CAN__',
    cheTopo: '__CHE__',
    // chlTopo: '__CHL__',
    chnTopo: '__CHN__',
    // civTopo: '__CIV__',
    clpTopo: '__CLP__',
    cmrTopo: '__CMR__',
    codTopo: '__COD__',
    cogTopo: '__COG__',
    cokTopo: '__COK__',
    colTopo: '__COL__',
    comTopo: '__COM__',
    cpvTopo: '__CPV__',
    criTopo: '__CRI__',
    csiTopo: '__CSI__',
    cubTopo: '__CUB__',
    cuwTopo: '__CUW__',
    cymTopo: '__CYM__',
    cynTopo: '__CYN__',
    cypTopo: '__CYP__',
    czeTopo: '__CZE__',
    deuTopo: '__DEU__',
    djiTopo: '__DJI__',
    dmaTopo: '__DMA__',
    dnkTopo: '__DNK__',
    domTopo: '__DOM__',
    // dzaTopo: '__DZA__',
    ecuTopo: '__ECU__',
    // egyTopo: '__EGY__',
    eriTopo: '__ERI__',
    esbTopo: '__ESB__',
    espTopo: '__ESP__',
    estTopo: '__EST__',
    ethTopo: '__ETH__',
    finTopo: '__FIN__',
    fjiTopo: '__FJI__',
    flkTopo: '__FLK__',
    // fraTopo: '__FRA__',
    froTopo: '__FRO__',
    fsmTopo: '__FSM__',
    gabTopo: '__GAB__',
    psxTopo: '__PSX__',
    gbrTopo: '__GBR__',
    geoTopo: '__GEO__',
    ggyTopo: '__GGY__',
    ghaTopo: '__GHA__',
    gibTopo: '__GIB__',
    ginTopo: '__GIN__',
    gmbTopo: '__GMB__',
    gnbTopo: '__GNB__',
    gnqTopo: '__GNQ__',
    grcTopo: '__GRC__',
    grdTopo: '__GRD__',
    grlTopo: '__GRL__',
    gtmTopo: '__GTM__',
    gumTopo: '__GUM__',
    guyTopo: '__GUY__',
    hkgTopo: '__HKG__',
    hmdTopo: '__HMD__',
    hndTopo: '__HND__',
    hrvTopo: '__HRV__',
    // htiTopo: '__HTI__',
    hunTopo: '__HUN__',
    idnTopo: '__IDN__',
    imnTopo: '__IMN__',
    indTopo: '__IND__',
    ioaTopo: '__IOA__',
    iotTopo: '__IOT__',
    irlTopo: '__IRL__',
    irnTopo: '__IRN__',
    // irqTopo: '__IRQ__',
    islTopo: '__ISL__',
    isrTopo: '__ISR__',
    // itaTopo: '__ITA__',
    jamTopo: '__JAM__',
    jeyTopo: '__JEY__',
    jorTopo: '__JOR__',
    jpnTopo: '__JPN__',
    kabTopo: '__KAB__',
    kasTopo: '__KAS__',
    kazTopo: '__KAZ__',
    kenTopo: '__KEN__',
    kgzTopo: '__KGZ__',
    khmTopo: '__KHM__',
    kirTopo: '__KIR__',
    knaTopo: '__KNA__',
    korTopo: '__KOR__',
    kosTopo: '__KOS__',
    kwtTopo: '__KWT__',
    laoTopo: '__LAO__',
    lbnTopo: '__LBN__',
    lbrTopo: '__LBR__',
    // lbyTopo: '__LBY__',
    lcaTopo: '__LCA__',
    lieTopo: '__LIE__',
    lkaTopo: '__LKA__',
    // lsoTopo: '__LSO__',
    ltuTopo: '__LTU__',
    luxTopo: '__LUX__',
    lvaTopo: '__LVA__',
    macTopo: '__MAC__',
    mafTopo: '__MAF__',
    marTopo: '__MAR__',
    mcoTopo: '__MCO__',
    mdaTopo: '__MDA__',
    // mdgTopo: '__MDG__',
    mdvTopo: '__MDV__',
    // mexTopo: '__MEX__',
    mhlTopo: '__MHL__',
    mkdTopo: '__MKD__',
    mliTopo: '__MLI__',
    // mltTopo: '__MLT__',
    mmrTopo: '__MMR__',
    mneTopo: '__MNE__',
    mngTopo: '__MNG__',
    mnpTopo: '__MNP__',
    mozTopo: '__MOZ__',
    mrtTopo: '__MRT__',
    msrTopo: '__MSR__',
    musTopo: '__MUS__',
    mwiTopo: '__MWI__',
    mysTopo: '__MYS__',
    namTopo: '__NAM__',
    nclTopo: '__NCL__',
    nerTopo: '__NER__',
    nfkTopo: '__NFK__',
    ngaTopo: '__NGA__',
    nicTopo: '__NIC__',
    niuTopo: '__NIU__',
    nldTopo: '__NLD__',
    nplTopo: '__NPL__',
    nruTopo: '__NRU__',
    nulTopo: '__NUL__',
    // nzlTopo: '__NZL__',
    omnTopo: '__OMN__',
    pakTopo: '__PAK__',
    panTopo: '__PAN__',
    pcnTopo: '__PCN__',
    perTopo: '__PER__',
    pgaTopo: '__PGA__',
    phlTopo: '__PHL__',
    plwTopo: '__PLW__',
    pngTopo: '__PNG__',
    polTopo: '__POL__',
    priTopo: '__PRI__',
    // prkTopo: '__PRK__',
    prtTopo: '__PRT__',
    pryTopo: '__PRY__',
    pyfTopo: '__PYF__',
    qatTopo: '__QAT__',
    rouTopo: '__ROU__',
    // rusTopo: '__RUS__',
    rwaTopo: '__RWA__',
    sahTopo: '__SAH__',
    // sauTopo: '__SAU__',
    scrTopo: '__SCR__',
    sdnTopo: '__SDN__',
    sdsTopo: '__SDS__',
    senTopo: '__SEN__',
    serTopo: '__SER__',
    sgpTopo: '__SGP__',
    sgsTopo: '__SGS__',
    shnTopo: '__SHN__',
    slbTopo: '__SLB__',
    sleTopo: '__SLE__',
    slvTopo: '__SLV__',
    smrTopo: '__SMR__',
    solTopo: '__SOL__',
    somTopo: '__SOM__',
    spmTopo: '__SPM__',
    srbTopo: '__SRB__',
    stpTopo: '__STP__',
    surTopo: '__SUR__',
    svkTopo: '__SVK__',
    svnTopo: '__SVN__',
    sweTopo: '__SWE__',
    swzTopo: '__SWZ__',
    sxmTopo: '__SXM__',
    // sycTopo: '__SYC__',
    // syrTopo: '__SYR__',
    tcaTopo: '__TCA__',
    // tcdTopo: '__TCD__',
    tgoTopo: '__TGO__',
    thaTopo: '__THA__',
    tjkTopo: '__TJK__',
    tkmTopo: '__TKM__',
    tlsTopo: '__TLS__',
    // tonTopo: '__TON__',
    ttoTopo: '__TTO__',
    tunTopo: '__TUN__',
    turTopo: '__TUR__',
    tuvTopo: '__TUV__',
    twnTopo: '__TWN__',
    tzaTopo: '__TZA__',
    ugaTopo: '__UGA__',
    // ukrTopo: '__UKR__',
    umiTopo: '__UMI__',
    uryTopo: '__URY__',
    usaTopo: '__USA__',
    usgTopo: '__USG__',
    uzbTopo: '__UZB__',
    vatTopo: '__VAT__',
    vctTopo: '__VCT__',
    venTopo: '__VEN__',
    vgbTopo: '__VGB__',
    virTopo: '__VIR__',
    vnmTopo: '__VNM__',
    vutTopo: '__VUT__',
    wlfTopo: '__WLF__',
    wsbTopo: '__WSB__',
    // wsmTopo: '__WSM__',
    // yemTopo: '__YEM__',
    zafTopo: '__ZAF__',
    zmbTopo: '__ZMB__',
    zweTopo: '__ZWE__'
};

export default topology;
